import type { SectorId } from "@/lib/sectors/types";
import type { StatementArchitecture } from "@/types/report";
import type { FinancialArchetype } from "@/lib/company-archetype";
import type { ResearchModuleId } from "@/lib/research-modules";
import type {
  ChartFamily,
  MaterialityDimension,
  MaterialityDimensionScores,
  TableFamily,
} from "./types";
import type { MaterialityTopicId } from "./proposal";
import type {
  EconomicIdentityType,
  SignatureAnalysisType,
} from "./proposal";

export interface MaterialityTopicDefinition {
  id: MaterialityTopicId;
  label: string;
  modules: ResearchModuleId[];
  dimensions: MaterialityDimensionScores;
  economicTypes?: EconomicIdentityType[];
  sectorIds?: SectorId[];
  architectures?: StatementArchitecture[];
  archetypes?: FinancialArchetype[];
}

const dims = (input: Partial<MaterialityDimensionScores>): MaterialityDimensionScores => ({
  earningsImpact: input.earningsImpact ?? 0,
  valuationImpact: input.valuationImpact ?? 0,
  thesisRelevance: input.thesisRelevance ?? 0,
  riskRelevance: input.riskRelevance ?? 0,
  uncertainty: input.uncertainty ?? 0,
  evidenceStrength: input.evidenceStrength ?? 0,
  balanceSheetImpact: input.balanceSheetImpact ?? 0,
  strategicImportance: input.strategicImportance ?? 0,
  investorAttention: input.investorAttention ?? 0,
  historicalAbnormality: input.historicalAbnormality ?? 0,
});

export const MATERIALITY_TOPIC_LABELS: Record<MaterialityTopicId, string> = {
  "growth-engine": "Growth engine",
  "margin-returns": "Margins and returns",
  "cash-conversion": "Cash conversion",
  "capital-allocation": "Capital allocation",
  "balance-sheet": "Balance sheet and solvency",
  "asset-quality": "Asset quality",
  "funding-liquidity": "Funding and liquidity",
  "segment-economics": "Segment economics",
  "sum-of-parts": "Sum of the parts",
  "project-pipeline": "Project pipeline",
  "unit-economics": "Unit economics",
  "volume-price-mix": "Volume, price and mix",
  "research-pipeline": "Research and product pipeline",
  "valuation-expectations": "Valuation and market expectations",
  "scenarios": "Scenarios and sensitivity",
  "management": "Management and governance",
  "risks": "Risks and invalidation",
  "catalysts": "Catalysts and events",
  "peers": "Relative positioning",
  "evidence": "Evidence and auditability",
};

export const MATERIALITY_DIMENSIONS: MaterialityDimension[] = [
  "earningsImpact",
  "valuationImpact",
  "thesisRelevance",
  "riskRelevance",
  "uncertainty",
  "evidenceStrength",
  "balanceSheetImpact",
  "strategicImportance",
  "investorAttention",
  "historicalAbnormality",
];

export const MATERIALITY_DIMENSION_WEIGHTS: Record<MaterialityDimension, number> = {
  earningsImpact: 0.16,
  valuationImpact: 0.15,
  thesisRelevance: 0.16,
  riskRelevance: 0.12,
  uncertainty: 0.08,
  evidenceStrength: 0.12,
  balanceSheetImpact: 0.08,
  strategicImportance: 0.07,
  investorAttention: 0.03,
  historicalAbnormality: 0.03,
};

export const MATERIALITY_TOPIC_DEFINITIONS: MaterialityTopicDefinition[] = [
  {
    id: "growth-engine",
    label: MATERIALITY_TOPIC_LABELS["growth-engine"],
    modules: ["business", "statements", "thesis"],
    dimensions: dims({ earningsImpact: 0.9, valuationImpact: 0.8, thesisRelevance: 0.9, uncertainty: 0.5, strategicImportance: 0.7, investorAttention: 0.7 }),
    economicTypes: ["subscription-platform", "transactional-platform", "unit-volume-business", "branded-volume-business", "cyclical-capital-business", "project-pipeline-business", "diversified-corporate"],
  },
  {
    id: "margin-returns",
    label: MATERIALITY_TOPIC_LABELS["margin-returns"],
    modules: ["statements", "moat", "valuation"],
    dimensions: dims({ earningsImpact: 0.85, valuationImpact: 0.8, thesisRelevance: 0.8, uncertainty: 0.45, strategicImportance: 0.6 }),
  },
  {
    id: "cash-conversion",
    label: MATERIALITY_TOPIC_LABELS["cash-conversion"],
    modules: ["statements", "quality", "valuation"],
    dimensions: dims({ earningsImpact: 0.6, valuationImpact: 0.7, thesisRelevance: 0.7, riskRelevance: 0.4, balanceSheetImpact: 0.5 }),
    economicTypes: ["subscription-platform", "branded-volume-business", "project-pipeline-business", "contracted-asset-business", "diversified-corporate"],
  },
  {
    id: "capital-allocation",
    label: MATERIALITY_TOPIC_LABELS["capital-allocation"],
    modules: ["management", "valuation", "thesis"],
    dimensions: dims({ earningsImpact: 0.5, valuationImpact: 0.7, thesisRelevance: 0.7, strategicImportance: 0.8, riskRelevance: 0.4 }),
  },
  {
    id: "balance-sheet",
    label: MATERIALITY_TOPIC_LABELS["balance-sheet"],
    modules: ["statements", "quality", "valuation"],
    dimensions: dims({ earningsImpact: 0.4, valuationImpact: 0.6, thesisRelevance: 0.6, riskRelevance: 0.7, balanceSheetImpact: 0.9 }),
  },
  {
    id: "asset-quality",
    label: MATERIALITY_TOPIC_LABELS["asset-quality"],
    modules: ["statements", "quality", "risk-catalyst"],
    dimensions: dims({ earningsImpact: 0.7, valuationImpact: 0.7, thesisRelevance: 0.7, riskRelevance: 0.9, balanceSheetImpact: 0.8 }),
    economicTypes: ["deposit-funded-bank", "lending-spread-finance"],
    sectorIds: ["bank", "nbfc"],
    architectures: ["B"],
  },
  {
    id: "funding-liquidity",
    label: MATERIALITY_TOPIC_LABELS["funding-liquidity"],
    modules: ["statements", "risk-catalyst", "quality"],
    dimensions: dims({ earningsImpact: 0.5, valuationImpact: 0.6, thesisRelevance: 0.6, riskRelevance: 0.8, balanceSheetImpact: 0.85 }),
    economicTypes: ["deposit-funded-bank", "lending-spread-finance", "distressed-turnaround"],
  },
  {
    id: "segment-economics",
    label: MATERIALITY_TOPIC_LABELS["segment-economics"],
    modules: ["business", "statements", "valuation"],
    dimensions: dims({ earningsImpact: 0.75, valuationImpact: 0.75, thesisRelevance: 0.75, uncertainty: 0.5, strategicImportance: 0.65 }),
    economicTypes: ["multi-segment-holding", "diversified-corporate", "contracted-asset-business"],
  },
  {
    id: "sum-of-parts",
    label: MATERIALITY_TOPIC_LABELS["sum-of-parts"],
    modules: ["business", "valuation", "thesis"],
    dimensions: dims({ earningsImpact: 0.6, valuationImpact: 0.95, thesisRelevance: 0.9, uncertainty: 0.5, strategicImportance: 0.7 }),
    economicTypes: ["multi-segment-holding"],
  },
  {
    id: "project-pipeline",
    label: MATERIALITY_TOPIC_LABELS["project-pipeline"],
    modules: ["business", "risk-catalyst", "valuation"],
    dimensions: dims({ earningsImpact: 0.75, valuationImpact: 0.7, thesisRelevance: 0.75, uncertainty: 0.65, strategicImportance: 0.7 }),
    economicTypes: ["project-pipeline-business", "contracted-asset-business"],
  },
  {
    id: "unit-economics",
    label: MATERIALITY_TOPIC_LABELS["unit-economics"],
    modules: ["business", "moat", "valuation"],
    dimensions: dims({ earningsImpact: 0.7, valuationImpact: 0.7, thesisRelevance: 0.8, uncertainty: 0.5, strategicImportance: 0.65 }),
    economicTypes: ["subscription-platform", "transactional-platform", "unit-volume-business"],
  },
  {
    id: "volume-price-mix",
    label: MATERIALITY_TOPIC_LABELS["volume-price-mix"],
    modules: ["business", "statements", "moat"],
    dimensions: dims({ earningsImpact: 0.75, valuationImpact: 0.65, thesisRelevance: 0.75, uncertainty: 0.45, strategicImportance: 0.6 }),
    economicTypes: ["branded-volume-business", "unit-volume-business", "pipeline-research-business"],
    sectorIds: ["consumer", "pharma", "auto", "cement", "agrochemical", "industrial"],
  },
  {
    id: "research-pipeline",
    label: MATERIALITY_TOPIC_LABELS["research-pipeline"],
    modules: ["business", "risk-catalyst", "thesis"],
    dimensions: dims({ earningsImpact: 0.65, valuationImpact: 0.65, thesisRelevance: 0.75, uncertainty: 0.7, strategicImportance: 0.7 }),
    economicTypes: ["pipeline-research-business"],
    sectorIds: ["pharma"],
  },
  {
    id: "valuation-expectations",
    label: MATERIALITY_TOPIC_LABELS["valuation-expectations"],
    modules: ["valuation", "thesis", "quality"],
    dimensions: dims({ earningsImpact: 0.3, valuationImpact: 0.95, thesisRelevance: 0.9, uncertainty: 0.6, investorAttention: 0.8 }),
  },
  {
    id: "scenarios",
    label: MATERIALITY_TOPIC_LABELS["scenarios"],
    modules: ["valuation", "risk-catalyst", "thesis"],
    dimensions: dims({ earningsImpact: 0.4, valuationImpact: 0.8, thesisRelevance: 0.75, riskRelevance: 0.6, uncertainty: 0.65 }),
  },
  {
    id: "management",
    label: MATERIALITY_TOPIC_LABELS["management"],
    modules: ["management", "quality", "thesis"],
    dimensions: dims({ earningsImpact: 0.35, valuationImpact: 0.45, thesisRelevance: 0.55, strategicImportance: 0.7, riskRelevance: 0.45 }),
  },
  {
    id: "risks",
    label: MATERIALITY_TOPIC_LABELS["risks"],
    modules: ["risk-catalyst", "quality", "thesis"],
    dimensions: dims({ earningsImpact: 0.6, valuationImpact: 0.7, thesisRelevance: 0.75, riskRelevance: 0.95, uncertainty: 0.6 }),
  },
  {
    id: "catalysts",
    label: MATERIALITY_TOPIC_LABELS["catalysts"],
    modules: ["risk-catalyst", "business", "thesis"],
    dimensions: dims({ earningsImpact: 0.55, valuationImpact: 0.65, thesisRelevance: 0.75, riskRelevance: 0.5, investorAttention: 0.7 }),
  },
  {
    id: "peers",
    label: MATERIALITY_TOPIC_LABELS["peers"],
    modules: ["peers", "valuation", "moat"],
    dimensions: dims({ earningsImpact: 0.35, valuationImpact: 0.6, thesisRelevance: 0.6, strategicImportance: 0.5, investorAttention: 0.5 }),
  },
  {
    id: "evidence",
    label: MATERIALITY_TOPIC_LABELS["evidence"],
    modules: ["quality", "thesis"],
    dimensions: dims({ earningsImpact: 0.25, valuationImpact: 0.35, thesisRelevance: 0.5, riskRelevance: 0.4, uncertainty: 0.7, evidenceStrength: 0.9 }),
  },
];

export interface SignatureCandidate {
  id: string;
  type: SignatureAnalysisType;
  title: string;
  question: string;
  topicId: MaterialityTopicId;
  chartIds: string[];
  tableIds: string[];
  sectionHints: string[];
  economicTypes?: EconomicIdentityType[];
  sectorIds?: SectorId[];
  architectures?: StatementArchitecture[];
  archetypes?: FinancialArchetype[];
  requiresModules: ResearchModuleId[];
  requiresDataSelectors: string[];
  minimumReferences: number;
  basePriority: number;
}

export const SIGNATURE_CANDIDATES: SignatureCandidate[] = [
  {
    id: "signature-balance-sheet-franchise",
    type: "balance-sheet-franchise",
    title: "Balance-sheet franchise decomposition",
    question: "Can deposit funding, credit pricing and operating efficiency sustain returns on equity?",
    topicId: "balance-sheet",
    chartIds: ["chart-bank-growth", "chart-bank-spread", "chart-asset-quality", "chart-capital"],
    tableIds: ["table-bank-franchise", "table-valuation-anchors"],
    sectionHints: ["fundamental-analysis", "credit-analysis-1", "capital-profitability", "bank-valuation"],
    economicTypes: ["deposit-funded-bank"],
    sectorIds: ["bank"],
    architectures: ["B"],
    requiresModules: ["business", "statements", "valuation"],
    requiresDataSelectors: ["annual-bank-spread", "annual-asset-quality", "annual-capital"],
    minimumReferences: 2,
    basePriority: 95,
  },
  {
    id: "signature-credit-cycle-stress",
    type: "credit-cycle-stress",
    title: "Credit-cycle stress test",
    question: "How much credit deterioration can earnings, provisions and capital absorb before valuation breaks?",
    topicId: "asset-quality",
    chartIds: ["chart-asset-quality", "chart-bank-growth", "chart-capital"],
    tableIds: ["table-asset-quality", "table-scenarios"],
    sectionHints: ["asset-quality", "scenario-stress", "credit-analysis-2"],
    economicTypes: ["lending-spread-finance", "deposit-funded-bank", "distressed-turnaround"],
    sectorIds: ["nbfc", "bank"],
    architectures: ["B"],
    requiresModules: ["statements", "risk-catalyst", "valuation"],
    requiresDataSelectors: ["annual-asset-quality", "valuation-scenarios"],
    minimumReferences: 2,
    basePriority: 92,
  },
  {
    id: "signature-volume-price-mix",
    type: "volume-price-mix",
    title: "Volume, price and mix decomposition",
    question: "Is growth coming from durable volume and premium mix, or from transient pricing and mix shifts?",
    topicId: "volume-price-mix",
    chartIds: ["chart-revenue-growth", "chart-profitability"],
    tableIds: ["table-statements", "table-unit-economics"],
    sectionHints: ["fundamental-analysis", "sector-economics", "competitive-landscape"],
    economicTypes: ["branded-volume-business", "unit-volume-business", "pipeline-research-business"],
    sectorIds: ["consumer", "pharma", "auto", "cement", "agrochemical", "industrial"],
    requiresModules: ["business", "statements", "moat"],
    requiresDataSelectors: ["annual-revenue", "annual-profitability"],
    minimumReferences: 1,
    basePriority: 88,
  },
  {
    id: "signature-pipeline-research",
    type: "pipeline-research-economics",
    title: "Research pipeline economics",
    question: "Does the product pipeline justify current research spending and the market's growth assumption?",
    topicId: "research-pipeline",
    chartIds: ["chart-research-intensity", "chart-revenue-growth"],
    tableIds: ["table-pipeline", "table-statements"],
    sectionHints: ["fundamental-analysis", "sector-economics", "scenario-valuation"],
    economicTypes: ["pipeline-research-business"],
    sectorIds: ["pharma"],
    requiresModules: ["business", "risk-catalyst", "thesis"],
    requiresDataSelectors: ["annual-revenue", "annual-research"],
    minimumReferences: 1,
    basePriority: 86,
  },
  {
    id: "signature-growth-margin-cash",
    type: "growth-margin-cash-bridge",
    title: "Growth-to-margin-to-cash bridge",
    question: "How much forecast growth converts into durable margins and free cash flow?",
    topicId: "cash-conversion",
    chartIds: ["chart-revenue-growth", "chart-profitability", "chart-cash-conversion"],
    tableIds: ["table-statements", "table-valuation-anchors"],
    sectionHints: ["fundamental-analysis", "analyst-forecasts", "relative-valuation"],
    economicTypes: ["subscription-platform", "transactional-platform", "branded-volume-business", "diversified-corporate"],
    requiresModules: ["statements", "valuation", "business"],
    requiresDataSelectors: ["annual-revenue", "annual-profitability", "annual-cash-conversion"],
    minimumReferences: 2,
    basePriority: 90,
  },
  {
    id: "signature-unit-economics",
    type: "unit-economics",
    title: "Unit economics",
    question: "What does one incremental customer, order, vehicle or subscriber contribute after variable cost?",
    topicId: "unit-economics",
    chartIds: ["chart-revenue-growth", "chart-profitability"],
    tableIds: ["table-unit-economics", "table-statements"],
    sectionHints: ["market-position", "fundamental-analysis", "sector-economics"],
    economicTypes: ["subscription-platform", "transactional-platform", "unit-volume-business"],
    requiresModules: ["business", "statements", "moat"],
    requiresDataSelectors: ["annual-revenue", "annual-profitability"],
    minimumReferences: 1,
    basePriority: 84,
  },
  {
    id: "signature-cycle-normalization",
    type: "cycle-normalization",
    title: "Cycle-normalized earnings",
    question: "Are current earnings structurally sustainable, or are they inflated or depressed by the cycle?",
    topicId: "margin-returns",
    chartIds: ["chart-revenue-growth", "chart-profitability", "chart-leverage"],
    tableIds: ["table-statements", "table-scenarios"],
    sectionHints: ["sector-economics", "fundamental-analysis", "scenario-stress"],
    economicTypes: ["cyclical-capital-business", "distressed-turnaround"],
    requiresModules: ["statements", "valuation", "risk-catalyst"],
    requiresDataSelectors: ["annual-revenue", "annual-profitability", "annual-leverage"],
    minimumReferences: 2,
    basePriority: 89,
  },
  {
    id: "signature-segment-value",
    type: "segment-value-bridge",
    title: "Segment value bridge",
    question: "What are the operating businesses worth separately, and what determines the holding-company discount?",
    topicId: "sum-of-parts",
    chartIds: ["chart-segments", "chart-valuation-scenarios"],
    tableIds: ["table-segments", "table-scenarios"],
    sectionHints: ["segment-map", "segment-valuation", "bridge-equity", "sotp-scenarios"],
    economicTypes: ["multi-segment-holding"],
    requiresModules: ["business", "valuation", "thesis"],
    requiresDataSelectors: ["valuation-segments", "valuation-scenarios"],
    minimumReferences: 2,
    basePriority: 94,
  },
  {
    id: "signature-contracted-cash-flow",
    type: "contracted-cash-flow",
    title: "Contracted cash-flow bridge",
    question: "How much projected cash flow is contracted, and what project or counterparty risk can interrupt it?",
    topicId: "project-pipeline",
    chartIds: ["chart-project-pipeline", "chart-cash-conversion"],
    tableIds: ["table-pipeline", "table-statements"],
    sectionHints: ["sector-economics", "catalysts-timeline", "scenario-valuation"],
    economicTypes: ["project-pipeline-business", "contracted-asset-business"],
    requiresModules: ["business", "statements", "risk-catalyst"],
    requiresDataSelectors: ["annual-revenue", "annual-cash-conversion"],
    minimumReferences: 1,
    basePriority: 87,
  },
  {
    id: "signature-asset-base",
    type: "asset-base-returns",
    title: "Asset-base return bridge",
    question: "Can occupancy, rents and balance-sheet discipline sustain distributions and net asset value?",
    topicId: "balance-sheet",
    chartIds: ["chart-reit-portfolio", "chart-reit-income", "chart-leverage"],
    tableIds: ["table-portfolio", "table-statements"],
    sectionHints: ["portfolio-occupancy", "nav-distributions", "reit-valuation"],
    economicTypes: ["asset-backed-business"],
    sectorIds: ["real-estate"],
    architectures: ["D"],
    requiresModules: ["business", "statements", "valuation"],
    requiresDataSelectors: ["annual-reit-portfolio", "annual-reit-income"],
    minimumReferences: 2,
    basePriority: 93,
  },
  {
    id: "signature-recovery",
    type: "recovery-bridge",
    title: "Earnings recovery bridge",
    question: "What must improve, in what order, for earnings and valuation to normalize?",
    topicId: "risks",
    chartIds: ["chart-revenue-growth", "chart-leverage", "chart-valuation-scenarios"],
    tableIds: ["table-statements", "table-scenarios", "table-risk-matrix"],
    sectionHints: ["situation-thesis", "scenario-valuation", "risks-invalidation"],
    economicTypes: ["distressed-turnaround"],
    archetypes: ["DISTRESSED"],
    requiresModules: ["statements", "valuation", "risk-catalyst"],
    requiresDataSelectors: ["annual-revenue", "annual-leverage", "valuation-scenarios"],
    minimumReferences: 2,
    basePriority: 91,
  },
  {
    id: "signature-capital-allocation",
    type: "capital-allocation-record",
    title: "Capital allocation record",
    question: "Has reinvestment, deleveraging and shareholder distributions created or destroyed value?",
    topicId: "capital-allocation",
    chartIds: ["chart-cash-conversion", "chart-leverage"],
    tableIds: ["table-capital-allocation", "table-statements"],
    sectionHints: ["capital-allocation", "management-2", "bridge-equity"],
    requiresModules: ["management", "statements", "valuation"],
    requiresDataSelectors: ["annual-cash-conversion", "annual-leverage"],
    minimumReferences: 1,
    basePriority: 80,
  },
  {
    id: "signature-expectations",
    type: "market-implied-expectations",
    title: "Market-implied expectations test",
    question: "What growth, margin and return assumptions are already embedded in the current share price?",
    topicId: "valuation-expectations",
    chartIds: ["chart-expectations", "chart-valuation-scenarios"],
    tableIds: ["table-valuation-anchors", "table-sensitivity"],
    sectionHints: ["fundamental-analysis", "scenario-valuation", "relative-valuation"],
    requiresModules: ["valuation", "thesis", "quality"],
    requiresDataSelectors: ["valuation-expectations", "valuation-scenarios"],
    minimumReferences: 2,
    basePriority: 96,
  },
  {
    id: "signature-earnings-power",
    type: "earnings-power-bridge",
    title: "Earnings-power bridge",
    question: "What revenue, margin and capital path supports the central valuation conclusion?",
    topicId: "margin-returns",
    chartIds: ["chart-revenue-growth", "chart-profitability"],
    tableIds: ["table-statements", "table-valuation-anchors"],
    sectionHints: ["fundamental-analysis", "analyst-forecasts", "methodology-1"],
    requiresModules: ["business", "statements", "valuation"],
    requiresDataSelectors: ["annual-revenue", "annual-profitability"],
    minimumReferences: 1,
    basePriority: 78,
  },
];

export interface ChartCandidate {
  id: string;
  title: string;
  family: ChartFamily;
  question: string;
  topicId: MaterialityTopicId;
  modules: ResearchModuleId[];
  dataSelector: string;
  decisionValue: string;
  economicTypes?: EconomicIdentityType[];
  sectorIds?: SectorId[];
  architectures?: StatementArchitecture[];
  signatureIds?: string[];
  requiredReferences: number;
  basePriority: number;
}

export const CHART_CANDIDATES: ChartCandidate[] = [
  {
    id: "chart-revenue-growth",
    title: "Revenue trajectory",
    family: "growth",
    question: "Is revenue growth durable across reported history?",
    topicId: "growth-engine",
    modules: ["statements", "business"],
    dataSelector: "annual-revenue",
    decisionValue: "Separates durable compounding from one-off revenue spikes.",
    requiredReferences: 1,
    basePriority: 80,
  },
  {
    id: "chart-profitability",
    title: "Profitability trajectory",
    family: "profitability",
    question: "Are margins expanding, stable or deteriorating?",
    topicId: "margin-returns",
    modules: ["statements", "moat"],
    dataSelector: "annual-profitability",
    decisionValue: "Tests operating leverage and pricing durability.",
    requiredReferences: 1,
    basePriority: 78,
  },
  {
    id: "chart-cash-conversion",
    title: "Cash conversion",
    family: "cash-flow",
    question: "How much reported profit becomes operating and free cash flow?",
    topicId: "cash-conversion",
    modules: ["statements", "quality"],
    dataSelector: "annual-cash-conversion",
    decisionValue: "Exposes accrual-heavy or reinvestment-heavy earnings.",
    requiredReferences: 1,
    basePriority: 76,
  },
  {
    id: "chart-leverage",
    title: "Leverage and solvency",
    family: "leverage",
    question: "Is leverage rising, stable or being repaired?",
    topicId: "balance-sheet",
    modules: ["statements", "quality"],
    dataSelector: "annual-leverage",
    decisionValue: "Determines downside and refinancing emphasis.",
    requiredReferences: 1,
    basePriority: 74,
  },
  {
    id: "chart-returns",
    title: "Returns on capital",
    family: "returns",
    question: "Do returns clear the cost of capital through the cycle?",
    topicId: "margin-returns",
    modules: ["statements", "moat", "valuation"],
    dataSelector: "annual-returns",
    decisionValue: "Separates compounders from capital-consuming growth.",
    requiredReferences: 1,
    basePriority: 72,
  },
  {
    id: "chart-bank-growth",
    title: "Loan and deposit growth",
    family: "funding",
    question: "Is balance-sheet growth funded by stable deposits or wholesale borrowing?",
    topicId: "balance-sheet",
    modules: ["business", "statements"],
    dataSelector: "annual-bank-spread",
    decisionValue: "Tests franchise quality and funding stability.",
    economicTypes: ["deposit-funded-bank", "lending-spread-finance"],
    sectorIds: ["bank", "nbfc"],
    architectures: ["B"],
    requiredReferences: 2,
    basePriority: 88,
  },
  {
    id: "chart-bank-spread",
    title: "Net interest margin and provisions",
    family: "profitability",
    question: "Is the lending spread sufficient after credit costs?",
    topicId: "margin-returns",
    modules: ["statements", "valuation"],
    dataSelector: "annual-bank-spread",
    decisionValue: "Explains bank earnings power and valuation sensitivity.",
    economicTypes: ["deposit-funded-bank", "lending-spread-finance"],
    sectorIds: ["bank", "nbfc"],
    architectures: ["B"],
    requiredReferences: 2,
    basePriority: 86,
  },
  {
    id: "chart-asset-quality",
    title: "Asset quality",
    family: "asset-quality",
    question: "Are problem loans rising or being resolved?",
    topicId: "asset-quality",
    modules: ["statements", "risk-catalyst", "quality"],
    dataSelector: "annual-asset-quality",
    decisionValue: "Determines credit-cycle and capital emphasis.",
    economicTypes: ["deposit-funded-bank", "lending-spread-finance"],
    sectorIds: ["bank", "nbfc"],
    architectures: ["B"],
    requiredReferences: 2,
    basePriority: 90,
  },
  {
    id: "chart-capital",
    title: "Capital adequacy",
    family: "capital",
    question: "Is capital sufficient for growth, stress and distributions?",
    topicId: "funding-liquidity",
    modules: ["statements", "quality", "valuation"],
    dataSelector: "annual-capital",
    decisionValue: "Determines balance-sheet constraint on the thesis.",
    economicTypes: ["deposit-funded-bank", "lending-spread-finance"],
    sectorIds: ["bank", "nbfc", "insurance"],
    architectures: ["B", "C"],
    requiredReferences: 2,
    basePriority: 84,
  },
  {
    id: "chart-reit-portfolio",
    title: "Occupancy and lease profile",
    family: "portfolio",
    question: "Is the portfolio leased, stable and economically occupied?",
    topicId: "segment-economics",
    modules: ["business", "statements"],
    dataSelector: "annual-reit-portfolio",
    decisionValue: "Tests rental durability and re-leasing risk.",
    economicTypes: ["asset-backed-business"],
    sectorIds: ["real-estate"],
    architectures: ["D"],
    requiredReferences: 2,
    basePriority: 88,
  },
  {
    id: "chart-reit-income",
    title: "Net operating income and funds from operations",
    family: "portfolio",
    question: "Do property operations convert into distributable funds?",
    topicId: "cash-conversion",
    modules: ["statements", "valuation"],
    dataSelector: "annual-reit-income",
    decisionValue: "Separates property operations from accounting net income.",
    economicTypes: ["asset-backed-business"],
    sectorIds: ["real-estate"],
    architectures: ["D"],
    requiredReferences: 2,
    basePriority: 86,
  },
  {
    id: "chart-research-intensity",
    title: "Research intensity and pipeline spend",
    family: "pipeline",
    question: "Is research spending proportionate to the pipeline opportunity?",
    topicId: "research-pipeline",
    modules: ["business", "statements"],
    dataSelector: "annual-research",
    decisionValue: "Tests whether pipeline optionality is funded efficiently.",
    economicTypes: ["pipeline-research-business"],
    sectorIds: ["pharma"],
    requiredReferences: 1,
    basePriority: 82,
  },
  {
    id: "chart-project-pipeline",
    title: "Project pipeline and execution",
    family: "pipeline",
    question: "Is contracted backlog converting into revenue and cash?",
    topicId: "project-pipeline",
    modules: ["business", "risk-catalyst"],
    dataSelector: "annual-revenue",
    decisionValue: "Tests execution against contracted demand.",
    economicTypes: ["project-pipeline-business", "contracted-asset-business"],
    requiredReferences: 1,
    basePriority: 80,
  },
  {
    id: "chart-segments",
    title: "Segment contribution",
    family: "growth",
    question: "Which businesses drive consolidated growth and value?",
    topicId: "segment-economics",
    modules: ["business", "valuation"],
    dataSelector: "valuation-segments",
    decisionValue: "Prevents a blended multiple from hiding segment economics.",
    economicTypes: ["multi-segment-holding"],
    requiredReferences: 2,
    basePriority: 92,
  },
  {
    id: "chart-valuation-scenarios",
    title: "Scenario valuation bridge",
    family: "scenarios",
    question: "How wide is the valuation range under bear, base and bull outcomes?",
    topicId: "scenarios",
    modules: ["valuation", "thesis"],
    dataSelector: "valuation-scenarios",
    decisionValue: "Quantifies asymmetry and downside protection.",
    requiredReferences: 2,
    basePriority: 82,
  },
  {
    id: "chart-expectations",
    title: "Market-implied expectations",
    family: "expectations",
    question: "What does the market already expect for growth and margins?",
    topicId: "valuation-expectations",
    modules: ["valuation", "thesis", "quality"],
    dataSelector: "valuation-expectations",
    decisionValue: "Determines whether the recommendation is an expectations bet.",
    requiredReferences: 2,
    basePriority: 94,
  },
  {
    id: "chart-sensitivity",
    title: "Valuation sensitivity",
    family: "sensitivity",
    question: "Which assumption moves fair value most?",
    topicId: "valuation-expectations",
    modules: ["valuation", "quality"],
    dataSelector: "valuation-sensitivity",
    decisionValue: "Focuses debate on the highest-leverage assumption.",
    requiredReferences: 1,
    basePriority: 70,
  },
  {
    id: "chart-peer-returns",
    title: "Peer returns and multiples",
    family: "comparison",
    question: "Is the company priced differently from economically similar peers?",
    topicId: "peers",
    modules: ["peers", "valuation"],
    dataSelector: "peer-comparison",
    decisionValue: "Tests relative valuation against a gated peer set.",
    requiredReferences: 1,
    basePriority: 68,
  },
  {
    id: "chart-events",
    title: "Event-driven price response",
    family: "events",
    question: "How has the market repriced material company events?",
    topicId: "catalysts",
    modules: ["risk-catalyst", "thesis"],
    dataSelector: "event-response",
    decisionValue: "Connects catalysts to observable repricing.",
    requiredReferences: 1,
    basePriority: 66,
  },
];

export interface TableCandidate {
  id: string;
  title: string;
  family: TableFamily;
  question: string;
  topicId: MaterialityTopicId;
  modules: ResearchModuleId[];
  dataSelector: string;
  decisionValue: string;
  economicTypes?: EconomicIdentityType[];
  sectorIds?: SectorId[];
  architectures?: StatementArchitecture[];
  signatureIds?: string[];
  requiredReferences: number;
  basePriority: number;
}

export const TABLE_CANDIDATES: TableCandidate[] = [
  {
    id: "table-statements",
    title: "Canonical statement summary",
    family: "statements",
    question: "What does reported history actually show?",
    topicId: "evidence",
    modules: ["statements", "quality"],
    dataSelector: "annual-statements",
    decisionValue: "Keeps every analytical claim anchored to reported lines.",
    requiredReferences: 1,
    basePriority: 75,
  },
  {
    id: "table-valuation-anchors",
    title: "Valuation anchors",
    family: "valuation",
    question: "What rating, target, fair value and current price anchor the conclusion?",
    topicId: "valuation-expectations",
    modules: ["valuation", "thesis"],
    dataSelector: "valuation-anchors",
    decisionValue: "Prevents narrative drift from the priced conclusion.",
    requiredReferences: 2,
    basePriority: 85,
  },
  {
    id: "table-scenarios",
    title: "Scenario matrix",
    family: "scenarios",
    question: "What happens to value if the central debate resolves either way?",
    topicId: "scenarios",
    modules: ["valuation", "risk-catalyst"],
    dataSelector: "valuation-scenarios",
    decisionValue: "Turns uncertainty into explicit bull, base and bear value.",
    requiredReferences: 1,
    basePriority: 78,
  },
  {
    id: "table-sensitivity",
    title: "Sensitivity grid",
    family: "sensitivity",
    question: "Which inputs deserve monitoring and debate?",
    topicId: "valuation-expectations",
    modules: ["valuation", "quality"],
    dataSelector: "valuation-sensitivity",
    decisionValue: "Prioritizes monitoring indicators.",
    requiredReferences: 1,
    basePriority: 68,
  },
  {
    id: "table-segments",
    title: "Segment economics",
    family: "segments",
    question: "How do segments differ in growth, margin and capital intensity?",
    topicId: "segment-economics",
    modules: ["business", "valuation"],
    dataSelector: "valuation-segments",
    decisionValue: "Supports segment-level valuation and capital allocation.",
    economicTypes: ["multi-segment-holding"],
    requiredReferences: 2,
    basePriority: 90,
  },
  {
    id: "table-bank-franchise",
    title: "Deposit franchise and spread",
    family: "funding",
    question: "How is the bank funded and priced?",
    topicId: "balance-sheet",
    modules: ["business", "statements"],
    dataSelector: "annual-bank-spread",
    decisionValue: "Makes deposit and spread economics explicit.",
    economicTypes: ["deposit-funded-bank", "lending-spread-finance"],
    sectorIds: ["bank", "nbfc"],
    architectures: ["B"],
    requiredReferences: 2,
    basePriority: 87,
  },
  {
    id: "table-asset-quality",
    title: "Asset-quality schedule",
    family: "asset-quality",
    question: "Where is credit risk concentrated and how is it covered?",
    topicId: "asset-quality",
    modules: ["statements", "risk-catalyst"],
    dataSelector: "annual-asset-quality",
    decisionValue: "Connects provisions, coverage and capital.",
    economicTypes: ["deposit-funded-bank", "lending-spread-finance"],
    sectorIds: ["bank", "nbfc"],
    architectures: ["B"],
    requiredReferences: 2,
    basePriority: 89,
  },
  {
    id: "table-portfolio",
    title: "Portfolio and lease schedule",
    family: "portfolio",
    question: "What leases, occupancy and expiries support rental income?",
    topicId: "segment-economics",
    modules: ["business", "statements"],
    dataSelector: "annual-reit-portfolio",
    decisionValue: "Tests contracted rental visibility.",
    economicTypes: ["asset-backed-business"],
    sectorIds: ["real-estate"],
    architectures: ["D"],
    requiredReferences: 2,
    basePriority: 86,
  },
  {
    id: "table-pipeline",
    title: "Pipeline and catalyst matrix",
    family: "pipeline",
    question: "Which pipeline items or projects matter, and what resolves them?",
    topicId: "project-pipeline",
    modules: ["business", "risk-catalyst"],
    dataSelector: "pipeline-matrix",
    decisionValue: "Turns pipeline optionality into monitorable catalysts.",
    economicTypes: ["pipeline-research-business", "project-pipeline-business", "contracted-asset-business"],
    requiredReferences: 1,
    basePriority: 80,
  },
  {
    id: "table-unit-economics",
    title: "Unit economics",
    family: "segments",
    question: "What economics does the marginal unit produce?",
    topicId: "unit-economics",
    modules: ["business", "moat"],
    dataSelector: "unit-economics",
    decisionValue: "Tests scalability of the economic engine.",
    economicTypes: ["subscription-platform", "transactional-platform", "unit-volume-business"],
    requiredReferences: 1,
    basePriority: 76,
  },
  {
    id: "table-capital-allocation",
    title: "Capital allocation record",
    family: "capital",
    question: "Where has cash gone, and what did shareholders receive?",
    topicId: "capital-allocation",
    modules: ["management", "statements"],
    dataSelector: "annual-cash-conversion",
    decisionValue: "Separates reinvestment discipline from distributions.",
    requiredReferences: 1,
    basePriority: 72,
  },
  {
    id: "table-peers",
    title: "Gated peer comparison",
    family: "peers",
    question: "How does the company compare with qualifying peers?",
    topicId: "peers",
    modules: ["peers", "valuation"],
    dataSelector: "peer-comparison",
    decisionValue: "Prevents relative valuation from an unqualified peer set.",
    requiredReferences: 1,
    basePriority: 70,
  },
  {
    id: "table-risk-matrix",
    title: "Risk and invalidation matrix",
    family: "risks",
    question: "What breaks the thesis, and what would warn investors first?",
    topicId: "risks",
    modules: ["risk-catalyst", "thesis"],
    dataSelector: "risk-matrix",
    decisionValue: "Makes downside explicit and monitorable.",
    requiredReferences: 1,
    basePriority: 74,
  },
  {
    id: "table-catalyst-matrix",
    title: "Catalyst matrix",
    family: "catalysts",
    question: "What could resolve the central debate?",
    topicId: "catalysts",
    modules: ["risk-catalyst", "thesis"],
    dataSelector: "catalyst-matrix",
    decisionValue: "Links upside to observable events.",
    requiredReferences: 1,
    basePriority: 73,
  },
  {
    id: "table-management",
    title: "Management and ownership record",
    family: "management",
    question: "Who governs capital, and how are incentives aligned?",
    topicId: "management",
    modules: ["management", "quality"],
    dataSelector: "management-record",
    decisionValue: "Keeps governance proportionate to its materiality.",
    requiredReferences: 1,
    basePriority: 62,
  },
  {
    id: "table-evidence",
    title: "Evidence register",
    family: "evidence",
    question: "Which sources support the material claims?",
    topicId: "evidence",
    modules: ["quality", "thesis"],
    dataSelector: "evidence-register",
    decisionValue: "Makes provenance inspectable.",
    requiredReferences: 1,
    basePriority: 64,
  },
];

export interface SectionIdentityHint {
  topicId: MaterialityTopicId;
  baseOrder: number;
  mandatory: boolean;
}

export const SECTION_IDENTITY_HINTS: Record<string, SectionIdentityHint> = {
  cover: { topicId: "evidence", baseOrder: 0, mandatory: true },
  "research-debates": { topicId: "valuation-expectations", baseOrder: 15, mandatory: false },
  "fundamental-analysis": { topicId: "margin-returns", baseOrder: 20, mandatory: false },
  "moat-price-fair-value": { topicId: "valuation-expectations", baseOrder: 35, mandatory: false },
  "moat-sources": { topicId: "segment-economics", baseOrder: 37, mandatory: false },
  "bulls-bears": { topicId: "risks", baseOrder: 65, mandatory: false },
  "credit-analysis-1": { topicId: "balance-sheet", baseOrder: 25, mandatory: false },
  "credit-analysis-2": { topicId: "funding-liquidity", baseOrder: 27, mandatory: false },
  "management-1": { topicId: "management", baseOrder: 55, mandatory: false },
  "management-2": { topicId: "capital-allocation", baseOrder: 57, mandatory: false },
  "event-price-movement": { topicId: "catalysts", baseOrder: 60, mandatory: false },
  "disclosures-catalysts": { topicId: "catalysts", baseOrder: 62, mandatory: false },
  "analyst-forecasts": { topicId: "growth-engine", baseOrder: 75, mandatory: false },
  "income-statement": { topicId: "growth-engine", baseOrder: 80, mandatory: false },
  "balance-sheet": { topicId: "balance-sheet", baseOrder: 82, mandatory: false },
  "cash-flow": { topicId: "cash-conversion", baseOrder: 84, mandatory: false },
  "comps-1": { topicId: "peers", baseOrder: 88, mandatory: false },
  "comps-2": { topicId: "peers", baseOrder: 90, mandatory: false },
  "methodology-1": { topicId: "evidence", baseOrder: 94, mandatory: false },
  "methodology-2": { topicId: "scenarios", baseOrder: 96, mandatory: false },
  "credit-rating-1": { topicId: "balance-sheet", baseOrder: 29, mandatory: false },
  "credit-rating-2": { topicId: "funding-liquidity", baseOrder: 31, mandatory: false },
  disclaimer: { topicId: "evidence", baseOrder: 110, mandatory: true },
  "analyst-ai-disclosure": { topicId: "evidence", baseOrder: 112, mandatory: false },
  "qa-checksum": { topicId: "evidence", baseOrder: 114, mandatory: true },
  "identity-overview": { topicId: "valuation-expectations", baseOrder: 8, mandatory: true },
  "signature-analysis": { topicId: "margin-returns", baseOrder: 33, mandatory: false },
};

export const SECTION_RHYTHM: Record<MaterialityTopicId, string[]> = {
  "growth-engine": ["Key question", "Revenue trajectory", "Driver interpretation", "Evidence table", "Valuation implication"],
  "margin-returns": ["Key question", "Margin trajectory", "Return interpretation", "Evidence table", "Valuation implication"],
  "cash-conversion": ["Cash question", "Cash trajectory", "Accrual interpretation", "Evidence table", "Valuation implication"],
  "capital-allocation": ["Allocation question", "Cash deployment", "Track-record interpretation", "Evidence table", "Conclusion"],
  "balance-sheet": ["Balance-sheet question", "Solvency trajectory", "Coverage interpretation", "Risk table", "Conclusion"],
  "asset-quality": ["Credit question", "Asset-quality trajectory", "Provision interpretation", "Risk table", "Valuation sensitivity"],
  "funding-liquidity": ["Funding question", "Liquidity schedule", "Maturity interpretation", "Risk table", "Downside conclusion"],
  "segment-economics": ["Segment question", "Contribution chart", "Segment interpretation", "Segment table", "Valuation implication"],
  "sum-of-parts": ["Valuation question", "Segment values", "Bridge interpretation", "Segment table", "Discount conclusion"],
  "project-pipeline": ["Pipeline question", "Backlog trajectory", "Execution interpretation", "Pipeline table", "Valuation implication"],
  "unit-economics": ["Unit question", "Unit trajectory", "Scale interpretation", "Unit table", "Margin implication"],
  "volume-price-mix": ["Demand question", "Volume and price trajectory", "Mix interpretation", "Evidence table", "Margin implication"],
  "research-pipeline": ["Pipeline question", "Spend trajectory", "Optionality interpretation", "Pipeline table", "Valuation implication"],
  "valuation-expectations": ["Central question", "Anchors", "Expectation chart", "Debate", "Conclusion"],
  "scenarios": ["Uncertainty question", "Scenario table", "Sensitivity interpretation", "Debate", "Asymmetry conclusion"],
  "management": ["Governance question", "Track record", "Incentive interpretation", "Ownership table", "Conclusion"],
  "risks": ["Risk question", "Exposure", "Scenario", "Valuation sensitivity", "Invalidation"],
  "catalysts": ["Catalyst question", "Timeline", "Transmission", "Evidence", "Conclusion"],
  "peers": ["Relative question", "Peer table", "Multiple interpretation", "Coverage caveat", "Conclusion"],
  "evidence": ["Provenance question", "Evidence register", "Gap interpretation", "Unknowns", "Audit conclusion"],
};

export const NARRATIVE_PROFILE_REGISTRY = {
  compounder: { fundamentalIntensity: 0.85, valuationIntensity: 0.65, forensicIntensity: 0.45, strategicIntensity: 0.55, eventIntensity: 0.25, creditIntensity: 0.3, quantitativeDensity: 0.75, skepticism: 0.45, evidenceRequirement: 0.7, scenarioEmphasis: 0.5, managementWeight: 0.55 },
  growth: { fundamentalIntensity: 0.8, valuationIntensity: 0.8, forensicIntensity: 0.35, strategicIntensity: 0.6, eventIntensity: 0.35, creditIntensity: 0.3, quantitativeDensity: 0.7, skepticism: 0.5, evidenceRequirement: 0.65, scenarioEmphasis: 0.7, managementWeight: 0.5 },
  forensic: { fundamentalIntensity: 0.7, valuationIntensity: 0.55, forensicIntensity: 0.95, strategicIntensity: 0.35, eventIntensity: 0.25, creditIntensity: 0.55, quantitativeDensity: 0.8, skepticism: 0.85, evidenceRequirement: 0.95, scenarioEmphasis: 0.45, managementWeight: 0.35 },
  credit: { fundamentalIntensity: 0.65, valuationIntensity: 0.55, forensicIntensity: 0.6, strategicIntensity: 0.35, eventIntensity: 0.25, creditIntensity: 0.95, quantitativeDensity: 0.75, skepticism: 0.7, evidenceRequirement: 0.8, scenarioEmphasis: 0.6, managementWeight: 0.3 },
  "deep-value": { fundamentalIntensity: 0.75, valuationIntensity: 0.85, forensicIntensity: 0.6, strategicIntensity: 0.4, eventIntensity: 0.25, creditIntensity: 0.6, quantitativeDensity: 0.7, skepticism: 0.75, evidenceRequirement: 0.8, scenarioEmphasis: 0.65, managementWeight: 0.35 },
  turnaround: { fundamentalIntensity: 0.7, valuationIntensity: 0.75, forensicIntensity: 0.55, strategicIntensity: 0.55, eventIntensity: 0.5, creditIntensity: 0.7, quantitativeDensity: 0.7, skepticism: 0.7, evidenceRequirement: 0.8, scenarioEmphasis: 0.8, managementWeight: 0.55 },
  conglomerate: { fundamentalIntensity: 0.75, valuationIntensity: 0.85, forensicIntensity: 0.5, strategicIntensity: 0.75, eventIntensity: 0.25, creditIntensity: 0.35, quantitativeDensity: 0.75, skepticism: 0.55, evidenceRequirement: 0.75, scenarioEmphasis: 0.65, managementWeight: 0.55 },
  "asset-backed": { fundamentalIntensity: 0.7, valuationIntensity: 0.7, forensicIntensity: 0.45, strategicIntensity: 0.45, eventIntensity: 0.25, creditIntensity: 0.6, quantitativeDensity: 0.7, skepticism: 0.55, evidenceRequirement: 0.7, scenarioEmphasis: 0.55, managementWeight: 0.4 },
  "event-driven": { fundamentalIntensity: 0.6, valuationIntensity: 0.7, forensicIntensity: 0.45, strategicIntensity: 0.55, eventIntensity: 0.95, creditIntensity: 0.4, quantitativeDensity: 0.6, skepticism: 0.6, evidenceRequirement: 0.75, scenarioEmphasis: 0.75, managementWeight: 0.5 },
  cyclical: { fundamentalIntensity: 0.75, valuationIntensity: 0.75, forensicIntensity: 0.55, strategicIntensity: 0.45, eventIntensity: 0.35, creditIntensity: 0.55, quantitativeDensity: 0.75, skepticism: 0.7, evidenceRequirement: 0.75, scenarioEmphasis: 0.8, managementWeight: 0.4 },
  strategic: { fundamentalIntensity: 0.7, valuationIntensity: 0.6, forensicIntensity: 0.4, strategicIntensity: 0.9, eventIntensity: 0.3, creditIntensity: 0.3, quantitativeDensity: 0.6, skepticism: 0.5, evidenceRequirement: 0.65, scenarioEmphasis: 0.55, managementWeight: 0.65 },
} as const;

export const VISUAL_PROFILE_REGISTRY = {
  compounder: { density: "balanced", chartFrequency: 0.65, tableFrequency: 0.65, calloutFrequency: 0.45, dividerStyle: "hairline", coverStructure: "metrics-led", typographyEmphasis: "metrics", chartEmphasis: "trend" },
  growth: { density: "balanced", chartFrequency: 0.75, tableFrequency: 0.55, calloutFrequency: 0.55, dividerStyle: "question-led", coverStructure: "question-led", typographyEmphasis: "question", chartEmphasis: "trend" },
  forensic: { density: "dense", chartFrequency: 0.55, tableFrequency: 0.85, calloutFrequency: 0.45, dividerStyle: "numbered-band", coverStructure: "evidence-led", typographyEmphasis: "evidence", chartEmphasis: "comparison" },
  credit: { density: "dense", chartFrequency: 0.6, tableFrequency: 0.85, calloutFrequency: 0.5, dividerStyle: "numbered-band", coverStructure: "metrics-led", typographyEmphasis: "metrics", chartEmphasis: "comparison" },
  "deep-value": { density: "balanced", chartFrequency: 0.6, tableFrequency: 0.7, calloutFrequency: 0.55, dividerStyle: "hairline", coverStructure: "valuation-led", typographyEmphasis: "valuation", chartEmphasis: "sensitivity" },
  turnaround: { density: "balanced", chartFrequency: 0.7, tableFrequency: 0.7, calloutFrequency: 0.6, dividerStyle: "question-led", coverStructure: "recovery-led", typographyEmphasis: "question", chartEmphasis: "comparison" },
  conglomerate: { density: "dense", chartFrequency: 0.7, tableFrequency: 0.8, calloutFrequency: 0.5, dividerStyle: "numbered-band", coverStructure: "segment-led", typographyEmphasis: "valuation", chartEmphasis: "composition" },
  "asset-backed": { density: "balanced", chartFrequency: 0.65, tableFrequency: 0.75, calloutFrequency: 0.45, dividerStyle: "hairline", coverStructure: "metrics-led", typographyEmphasis: "metrics", chartEmphasis: "comparison" },
  "event-driven": { density: "spacious", chartFrequency: 0.6, tableFrequency: 0.55, calloutFrequency: 0.7, dividerStyle: "question-led", coverStructure: "question-led", typographyEmphasis: "question", chartEmphasis: "trend" },
  cyclical: { density: "balanced", chartFrequency: 0.75, tableFrequency: 0.6, calloutFrequency: 0.5, dividerStyle: "hairline", coverStructure: "valuation-led", typographyEmphasis: "valuation", chartEmphasis: "trend" },
} as const;
