/**
 * APEX RESEARCH — AI NARRATIVE BUILDERS
 *
 * Thesis, catalysts, risks, competitive analysis, and moat — all dynamically
 * generated by AI from the company's fact pack and model outputs. No fixed
 * moat pillars, no hardcoded peer lists, no generic risk templates.
 *
 * Every quantitative statement must link back to a yfinance FACT or an AI
 * MODEL OUTPUT. The AI never invents unsupported numbers.
 */
import type {
  FactPack,
  CompanyUnderstanding,
  ForecastSpecification,
  ThesisSpecification,
  Catalyst,
  Risk,
  CompetitorAnalysis,
  MoatAnalysis,
} from "./types";
import { parseLlmJson } from "./llm";

export type NarrativeTransport = (opts: {
  system: string;
  user: string;
  temperature?: number;
  maxTokens?: number;
  jsonMode?: boolean;
}) => Promise<string>;

const SYSTEM_PROMPT = `You are an institutional equity research analyst. Generate the qualitative research narrative for this company: investment thesis, catalysts, risks, competitive analysis, and moat.

RULES:
- Every quantitative statement must cite a yfinance fact ID [F-...] or an AI model output.
- Risks must be company-specific with mechanism → affected KPI → financial consequence → valuation consequence → monitoring indicator. Not generic "competition" or "macro risk" unless you explain why those matter HERE.
- Catalysts: for each, establish the chain: catalyst → business mechanism → financial variable → forecast impact → valuation impact. If you cannot establish a quantitative chain, set "quantitative": false (QUALITATIVE ONLY). Do NOT invent percentage valuation impacts.
- Competitive analysis: you determine relevant competitors from the business model. If appropriate peers cannot be identified, set "insufficient": true. Explain overlap, economic similarity, key difference, strengths, weaknesses.
- Moat: you determine the competitive advantage sources from the company — cost advantage, brand, network effects, switching costs, distribution, scale, technology, regulatory position, IP, data, customer relationships — selecting only what applies. Do NOT force five pillars.

Respond with ONLY JSON:
{
  "thesis": {
    "thesis": "string",
    "bullCase": ["string"],
    "bearCase": ["string"],
    "keyDebate": "string",
    "keyInflectionPoints": ["string"],
    "whatMarketMayBeMissing": "string",
    "whatCouldInvalidate": ["string"]
  },
  "catalysts": [{ "catalyst": "string", "mechanism": "string", "financialVariable": "string", "forecastImpact": "string", "valuationImpact": "string", "quantitative": true, "timeframe": "string" }],
  "risks": [{ "risk": "string", "mechanism": "string", "affectedKpi": "string", "financialConsequence": "string", "valuationConsequence": "string", "monitoringIndicator": "string" }],
  "competitiveAnalysis": { "competitors": [{ "company": "string", "businessOverlap": "string", "economicSimilarity": "string", "keyDifference": "string", "relativeStrengths": "string", "relativeWeaknesses": "string" }], "insufficient": false },
  "moat": { "hasMoat": true, "sources": [{ "source": "string", "evidence": "string", "economicConsequence": "string", "durability": "string", "threatsToDurability": "string" }], "verdict": "string" }
}`;

/** Compact NARRATIVE_CONTEXT: understanding + model anchors only (Principle 33). */
export function narrativeContext(
  pack: FactPack,
  understanding: CompanyUnderstanding,
  modelSpec: ForecastSpecification
): string {
  const clip = (s: string, n: number) => (s.length > n ? s.slice(0, n) + "…" : s);
  const incomeAnchors = pack.incomeStatement.facts
    .filter((f) => f.value !== undefined)
    .slice(0, 12)
    .map((f) => `- [F-${f.metric}] (${f.period}): ${f.value}`);
  return [
    `COMPANY: ${understanding.companyName} (${pack.ticker})`,
    `What it does: ${clip(understanding.whatItDoes, 700)}`,
    `How it makes money: ${clip(understanding.howItMakesMoney, 500)}`,
    `Primary economic abstraction: ${understanding.primaryEconomicAbstraction}`,
    `Industry context: ${clip(understanding.industryContext, 500)}`,
    "",
    "REVENUE DRIVERS:",
    ...understanding.revenueDrivers.map((d) => `- ${d.name}: ${d.mechanism}`),
    "",
    "KEY KPIS:",
    ...understanding.keyKpis.map((k) => `- ${k.name} (${k.availability}): ${k.rationale}`),
    "",
    "METRICS TO AVOID (determined by the understanding stage):",
    ...understanding.metricsToAvoid.map((m) => `- ${m.metric} — ${m.reason}`),
    "",
    "FORECAST ASSUMPTIONS (AI model outputs):",
    ...modelSpec.assumptions.map((a) => `- ${a.variable}: ${a.value} ${a.unit} — ${a.assumption}`),
    "",
    "HISTORICAL FACT ANCHORS (yfinance):",
    ...incomeAnchors,
  ].join("\n");
}

export interface NarrativeOutput {
  thesis: ThesisSpecification;
  catalysts: Catalyst[];
  risks: Risk[];
  competitiveAnalysis: CompetitorAnalysis;
  moat: MoatAnalysis;
}

/** AI narrative generation from fact pack + model spec. */
export async function buildNarrative(
  transport: NarrativeTransport,
  pack: FactPack,
  understanding: CompanyUnderstanding,
  modelSpec: ForecastSpecification
): Promise<NarrativeOutput> {
  const ctx = narrativeContext(pack, understanding, modelSpec);
  const user = `Write the research narrative (thesis, catalysts, risks, competitive analysis, moat) for ${understanding.companyName} now. Respond with ONLY the JSON object.`;

  const resp = await transport({ system: SYSTEM_PROMPT, user, temperature: 0.4, maxTokens: 3500, jsonMode: true });
  const parsed = parseLlmJson<Record<string, any>>(resp);
  if (!parsed) {
    throw new Error(`AI narrative builder returned unparseable output for ${pack.ticker}`);
  }

  const t = parsed.thesis || {};
  const thesis: ThesisSpecification = {
    thesis: String(t.thesis || ""),
    bullCase: Array.isArray(t.bullCase) ? t.bullCase.map(String) : [],
    bearCase: Array.isArray(t.bearCase) ? t.bearCase.map(String) : [],
    keyDebate: String(t.keyDebate || ""),
    keyInflectionPoints: Array.isArray(t.keyInflectionPoints) ? t.keyInflectionPoints.map(String) : [],
    whatMarketMayBeMissing: String(t.whatMarketMayBeMissing || ""),
    whatCouldInvalidate: Array.isArray(t.whatCouldInvalidate) ? t.whatCouldInvalidate.map(String) : [],
  };

  const catalysts: Catalyst[] = (Array.isArray(parsed.catalysts) ? parsed.catalysts : []).map((c: any) => ({
    catalyst: String(c?.catalyst || ""),
    mechanism: String(c?.mechanism || ""),
    financialVariable: String(c?.financialVariable || ""),
    forecastImpact: typeof c?.forecastImpact === "string" ? c.forecastImpact : undefined,
    valuationImpact: typeof c?.valuationImpact === "string" ? c.valuationImpact : undefined,
    quantitative: c?.quantitative === true,
    timeframe: typeof c?.timeframe === "string" ? c.timeframe : undefined,
  }));

  const risks: Risk[] = (Array.isArray(parsed.risks) ? parsed.risks : []).map((r: any) => ({
    risk: String(r?.risk || ""),
    mechanism: String(r?.mechanism || ""),
    affectedKpi: String(r?.affectedKpi || ""),
    financialConsequence: String(r?.financialConsequence || ""),
    valuationConsequence: String(r?.valuationConsequence || ""),
    monitoringIndicator: String(r?.monitoringIndicator || ""),
  }));

  const comp = parsed.competitiveAnalysis || {};
  const competitiveAnalysis: CompetitorAnalysis = {
    competitors: (Array.isArray(comp.competitors) ? comp.competitors : []).map((c: any) => ({
      company: String(c?.company || ""),
      businessOverlap: String(c?.businessOverlap || ""),
      economicSimilarity: String(c?.economicSimilarity || ""),
      keyDifference: String(c?.keyDifference || ""),
      relativeStrengths: String(c?.relativeStrengths || ""),
      relativeWeaknesses: String(c?.relativeWeaknesses || ""),
    })),
    insufficient: comp.insufficient === true,
    note: typeof comp.note === "string" ? comp.note : undefined,
  };

  const mo = parsed.moat || {};
  const moat: MoatAnalysis = {
    hasMoat: mo.hasMoat === true,
    sources: (Array.isArray(mo.sources) ? mo.sources : []).map((s: any) => ({
      source: String(s?.source || ""),
      evidence: String(s?.evidence || ""),
      economicConsequence: String(s?.economicConsequence || ""),
      durability: String(s?.durability || ""),
      threatsToDurability: String(s?.threatsToDurability || ""),
    })),
    verdict: String(mo.verdict || ""),
  };

  return { thesis, catalysts, risks, competitiveAnalysis, moat };
}

export default { buildNarrative, narrativeContext };