/**
 * APEX RESEARCH — AI NARRATIVE BUILDERS
 *
 * Thesis, catalysts, risks, competitive analysis, and moat — all dynamically
 * generated by AI from the company's fact pack and model outputs. No fixed
 * moat pillars, no hardcoded peer lists, no generic risk templates.
 *
 * Every quantitative statement must link back to a yfinance FACT or an AI
 * MODEL OUTPUT. The AI never invents unsupported numbers.
 */
import type {
  FactPack,
  CompanyUnderstanding,
  ForecastSpecification,
  ThesisSpecification,
  Catalyst,
  Risk,
  CompetitorAnalysis,
  MoatAnalysis,
  EconomicEngine,
  ThesisEngineOutput,
  EvidenceMap,
  ResearchDiscoveryPack,
} from "./types";
import { parseLlmJson } from "./llm";
import { buildAnalystBrief, renderAnalystBrief } from "./analyst-brief";
import { buildHistoricalAnalysisPack, renderHistoricalAnalysisPack } from "./historical-analysis";
import { renderResearchDiscovery } from "./research-discovery";
import { DEPTH_DIRECTIVES, DEPTH_TOKEN_BUDGETS } from "./depth-guidance";

export type NarrativeTransport = (opts: {
  system: string;
  user: string;
  temperature?: number;
  maxTokens?: number;
  jsonMode?: boolean;
}) => Promise<string>;

const SYSTEM_PROMPT = `You are an institutional equity research analyst (Writer role). You receive the canonical Analyst Brief — company identity, economic engine, DERIVED historical trajectory (CAGR, margins, ROE, FCF, leverage — not raw rows), forecast assumptions from ONE canonicalForecast (cover/SCENARIO/DCF single object, no parallel model), valuation, scenarios, contradictions, missing information, research debates with evidence maps, and the full [F-...] evidence table plus filing segment registry when available.

YOU EXPLAIN RESEARCH. YOU DO NOT CREATE NEW QUANTITATIVE CLAIMS.

RESEARCHER→WRITER: Before writing, think as Researcher:
What do we know (Tier1 filing / Tier4 yfinance fact [F-...])? What don't we know (requires filings/calls)? What changed (trailing → Y1 gap)? What matters (driver that moves valuation)? What contradicts (e.g., Other Operating Expense disappearing, 62.5% vs 30% margin fork)? What is unusual? What is the key debate? What evidence supports vs challenges the thesis?

THESIS (company-specific core debate, NOT generic):
- Open with the CENTRAL research debate (e.g., MSFT: "Can AI-driven Azure/productivity monetization outgrow AI-infrastructure capital intensity?"), not a slogan.
- THESIS CHAIN (mandatory): EVIDENCE [F-...] or canonical forecast assumption → MECHANISM (e.g., Azure consumption, M365 seats, Copilot adoption → workflow lock → pricing power) → AFFECTED KPI → FINANCIAL CONSEQUENCE (revenue/EBIT/FCF/capex) → VALUATION CONSEQUENCE (EV/equity/per-share).
- Provide evidence FOR the bull reading, evidence AGAINST, financial consequence of each side, valuation consequence, and invalidation. Do NOT just list bull/bear bullets with no mechanism.

CATALYSTS — structure for each:
event / timing (timeframe) / observable KPI / direction (positive|negative|mixed) / forecast impact (canonical variable) / valuation impact / invalidation (what would delay or kill the catalyst).
Generic "earnings beat / margin expansion" without a real event is blocked. If no quantitative chain, quantitative=false (QUALITATIVE ONLY). Do NOT invent % impacts.

MOAT — economic architecture chains, not pillar labels:
Each source must be a chain: asset → mechanism → KPI → financial → valuation.
Examples of required form: "M365 → workflow integration → switching costs → seat pricing power → recurring revenue"; "Azure → workload migration → dependency → consumption"; "ecosystem → cross-sell → LTV".
Evidence [F-...] or ROCE vs WACC / margin stability. If no durable advantage evidenced, hasMoat=false.

COMPETITIVE — real rivals and real drivers only (for software: AWS, Google Cloud, not generic peers). Segment-level when filing registry holds segments. Compare on THIS company's drivers (Azure consumption, M365 seats, Copilot adoption), not brand adjectives. insufficient=true when evidence is thin.

RULES:
- Thesis is DEBATE-DRIVEN + CHAIN-DRIVEN: use the research debates provided when present; state what would prove you WRONG + monitoring KPI + explicit Other Operating Expense classification if material historically (RECURRING/NON_RECURRING/RECLASSIFIED).
- Every quantitative statement must cite a yfinance fact ID [F-...] or the canonical forecast assumption/output. Tier6 inference alone = low confidence. Cover/Scenario/DCF numbers must match canonicalForecast verbatim.
- Evidence-constrained output: if you cannot support a catalyst/risk/competitor/moat source with evidence, OMIT it. A report with 20 generic warnings is BLOCKED, not READY_WITH_WARNINGS.
- Risks: mechanism → affected KPI (company-native) → financial consequence → valuation consequence → monitoring indicator.
- Do not invent new numbers the forecast/valuation stages did not compute.
- RESEARCH DISCOVERY SEEDS: context may include a discovery pack (coverage + moat/catalyst/risk/competitive seeds + economic insights like margin mechanism, working-capital chain, ROIC interpretation, target-price methodology). EXPLAIN those seeds as chains — never leave thesis/catalyst/risk/moat/competitive blank while usable seeds exist. If coverage marks an area "missing", state the gap honestly instead of inventing. Seeds tagged Tier-6 stay inference.

${DEPTH_DIRECTIVES.narrative}

Respond with ONLY JSON:
{
  "thesis": {
    "thesis": "string (opens with central debate + chain)",
    "bullCase": ["string (evidence→mechanism→KPI→financial→valuation)"],
    "bearCase": ["string (evidence→mechanism→KPI→financial→valuation)"],
    "keyDebate": "string",
    "keyInflectionPoints": ["string"],
    "whatMarketMayBeMissing": "string",
    "whatCouldInvalidate": ["string"]
  },
  "catalysts": [{ "catalyst": "string", "mechanism": "string", "financialVariable": "string", "forecastImpact": "string", "valuationImpact": "string", "quantitative": true, "timeframe": "string", "observableKpi": "string", "direction": "positive", "invalidation": "string" }],
  "risks": [{ "risk": "string", "mechanism": "string", "affectedKpi": "string", "financialConsequence": "string", "valuationConsequence": "string", "monitoringIndicator": "string" }],
  "competitiveAnalysis": { "competitors": [{ "company": "string", "businessOverlap": "string", "economicSimilarity": "string", "keyDifference": "string", "relativeStrengths": "string", "relativeWeaknesses": "string", "segment": "string" }], "insufficient": false },
  "moat": { "hasMoat": true, "sources": [{ "source": "string", "evidence": "string", "economicConsequence": "string", "durability": "string", "threatsToDurability": "string", "chain": "asset→mechanism→KPI→financial→valuation" }], "verdict": "string" }
}`;

/** Rich NARRATIVE_CONTEXT with filing segments, canonical basis, PP&E economics, and chain-ready KPIs. */
export function narrativeContext(
  pack: FactPack,
  understanding: CompanyUnderstanding,
  modelSpec: ForecastSpecification,
  canonicalForecast?: any,
  extras?: {
    engine?: EconomicEngine;
    debates?: ThesisEngineOutput;
    evidenceMap?: EvidenceMap;
    discovery?: ResearchDiscoveryPack;
    /** Deterministic ResearchDNA depth emphasis (see depth-guidance.depthBriefForIdentity). */
    depthBrief?: string;
  }
): string {
  const engine = extras?.engine;
  const debates = extras?.debates;
  const evidenceMap = extras?.evidenceMap;
  const discovery = extras?.discovery;
  // Prefer canonical AnalystBrief — falls back to legacy compact if brief unavailable
  try {
    const brief = buildAnalystBrief({ pack, understanding, forecastSpec: modelSpec });
    // Inject filing segments when registry holds PRIMARY data (segment-level comps)
    try {
      const { getFilingSegments } = require("../filing-segments") as typeof import("../filing-segments");
      const segs = getFilingSegments(pack.ticker);
      if (segs) {
        (brief as any).filingSegments = segs;
        brief.evidenceLines.push(`FILING SEGMENTS (PRIMARY): ${segs.segments.map((s: any) => `${s.name} rev ${s.revenue ?? "n/a"} EBITDA ${s.ebitda} — ${s.sourceDoc} ${s.period}`).join(" | ")}`);
      }
    } catch {}
    // Inject canonical basis for chain: capex PPE-anchored, D&A, OtherOpex classification, continuity
    if (canonicalForecast?.basis) {
      const b = canonicalForecast.basis;
      brief.evidenceLines.push(`CANONICAL BASIS capex: ${b.capex ?? b.capex}`);
      brief.evidenceLines.push(`CANONICAL BASIS depreciation: ${b.depreciation ?? b.depreciation}`);
      if (b.otherOperatingExpense) brief.evidenceLines.push(`CANONICAL BASIS otherOperatingExpense: ${b.otherOperatingExpense}`);
      if (b.continuity) brief.evidenceLines.push(`CANONICAL BASIS continuity: ${b.continuity}`);
    }
    if (understanding.whyThisCompany) brief.evidenceLines.push(`WHY THIS COMPANY: ${understanding.whyThisCompany}`);
    for (const a of understanding.competitiveAdvantages || []) {
      brief.evidenceLines.push(`COMPETITIVE ADVANTAGE: ${a.advantage} — ${a.mechanism}`);
    }
    for (const t of understanding.competitiveThreats || []) {
      brief.evidenceLines.push(`COMPETITIVE THREAT: ${t.threat} — ${t.mechanism}`);
    }
    if (engine?.valueQuestions?.length) brief.evidenceLines.push(`ENGINE VALUE QUESTIONS: ${engine.valueQuestions.join(" | ")}`);
    if (debates?.debates?.length) {
      brief.coreDebate = debates.debates[debates.centralDebateIndex]?.debate || brief.coreDebate;
      for (const d of debates.debates) {
        brief.evidenceLines.push(
          `RESEARCH DEBATE: ${d.debate} | FOR: ${d.evidenceFor.map((e) => e.evidence).join("; ")} | AGAINST: ${d.evidenceAgainst.map((e) => e.evidence).join("; ")} | financial: ${d.financialConsequence || "n/a"} | valuation: ${d.valuationConsequence || "n/a"} | resolution: ${d.resolutionSignal || "n/a"}`
        );
      }
      brief.evidenceLines.push(`CENTRAL THESIS (debate stage): ${debates.thesis}`);
      brief.evidenceLines.push(`INVALIDATION: ${debates.invalidationCondition} | MONITOR: ${debates.monitoringKpi}`);
    }
    if (evidenceMap) {
      brief.evidenceLines.push(`EVIDENCE MAP confidence: ${evidenceMap.overallConfidence.toFixed(2)}; unsupported claims: ${evidenceMap.unsupported.slice(0, 5).join(" | ") || "none"}`);
      for (const item of evidenceMap.items.slice(0, 12)) {
        brief.evidenceLines.push(`EVIDENCE [${item.direction}/T${item.tier}/c${item.confidence.toFixed(2)}]: ${item.claim} — ${item.evidence.slice(0, 160)} ${item.factIds.join(" ")}`);
      }
    }
    if (discovery) {
      brief.evidenceLines.push(renderResearchDiscovery(discovery).slice(0, 6000));
      const missing = discovery.gaps.filter((g) => g.status === "missing");
      for (const g of missing.slice(0, 6)) {
        brief.missingInformation.push(`${g.area}: ${g.question} (${g.why})`);
      }
      brief.missingInformation = [...new Set(brief.missingInformation)];
    }
    if (extras?.depthBrief) brief.evidenceLines.push(extras.depthBrief.slice(0, 2000));
    return renderAnalystBrief(brief as any);
  } catch {}
  const clip = (s: string, n: number) => (s.length > n ? s.slice(0, n) + "…" : s);
  // Full evidence packet: income + balance + cash + market anchors + derived metrics
  const allAnchors = [
    ...pack.incomeStatement.facts,
    ...pack.balanceSheet.facts,
    ...pack.cashFlow.facts,
  ].filter((f) => f.value !== undefined).slice(0, 40).map((f) => `- [F-${f.metric}] (${f.period}): ${f.value}`);
  let derived = "";
  try {
    derived = renderHistoricalAnalysisPack(buildHistoricalAnalysisPack(pack));
  } catch { derived = "(derived metrics unavailable)"; }
  // Filing segment injection for non-brief path
  let segmentBlock = "";
  try {
    const { getFilingSegments } = require("../filing-segments") as typeof import("../filing-segments");
    const segs = getFilingSegments(pack.ticker);
    if (segs) segmentBlock = `FILING SEGMENTS (PRIMARY — use for segment-level competitive matrix):\n${segs.segments.map((s: any) => `- ${s.name}: rev ${s.revenue ?? "n/a"} EBITDA ${s.ebitda} — ${s.sourceDoc} ${s.period}`).join("\n")}\n`;
  } catch {}
  // Append segment block if present (segment-level comps for conglomerates)
  const segmentSection = segmentBlock ? [segmentBlock] : [];
  // Append canonical basis if available (for fallback path)
  let canonicalBasisBlock = "";
  try {
    if (canonicalForecast?.basis) {
      canonicalBasisBlock = `CANONICAL BASIS (single object — cover/Scenario/DCF must match verbatim):\n` +
        `capex: ${canonicalForecast.basis.capex ?? ""}\n` +
        `depreciation: ${canonicalForecast.basis.depreciation ?? ""}\n` +
        `otherOperatingExpense: ${canonicalForecast.basis.otherOperatingExpense ?? ""}\n` +
        `continuity: ${canonicalForecast.basis.continuity ?? ""}\n`;
    }
  } catch {}
  const debateBlock = debates?.debates?.length
    ? [
        "",
        "RESEARCH DEBATES (drive thesis — explain, do not invent):",
        ...debates.debates.map(
          (d) =>
            `- ${d.debate}\n  FOR: ${d.evidenceFor.map((e) => e.evidence).join("; ")}\n  AGAINST: ${d.evidenceAgainst.map((e) => e.evidence).join("; ")}\n  financial: ${d.financialConsequence || "n/a"} | valuation: ${d.valuationConsequence || "n/a"} | resolution: ${d.resolutionSignal || "n/a"}`
        ),
        `CENTRAL THESIS: ${debates.thesis}`,
        `INVALIDATION: ${debates.invalidationCondition} | MONITOR: ${debates.monitoringKpi}`,
      ]
    : [];
  const discoveryBlock = discovery
    ? ["", "RESEARCH DISCOVERY SEEDS (explain — do not invent beyond seeds):", renderResearchDiscovery(discovery).slice(0, 6000)]
    : [];
  const depthBlock = extras?.depthBrief ? ["", extras.depthBrief.slice(0, 2000)] : [];
  return [
    `COMPANY: ${understanding.companyName} (${pack.ticker})`,
    `What it does: ${clip(understanding.whatItDoes, 700)}`,
    `How it makes money: ${clip(understanding.howItMakesMoney, 500)}`,
    `Primary economic abstraction: ${understanding.primaryEconomicAbstraction}`,
    `Why this company: ${clip(understanding.whyThisCompany || "", 400) || "(n/a)"}`,
    `Industry context: ${clip(understanding.industryContext, 500)}`,
    ...(engine?.valueQuestions?.length ? [`Engine value questions: ${engine.valueQuestions.join(" | ")}`] : []),
    ...(segmentSection.length ? ["", ...segmentSection] : []),
    ...(canonicalBasisBlock ? ["", canonicalBasisBlock] : []),
    ...debateBlock,
    ...discoveryBlock,
    ...depthBlock,
    "",
    "REVENUE DRIVERS:",
    ...understanding.revenueDrivers.map((d) => `- ${d.name}: ${d.mechanism}`),
    "COST DRIVERS:",
    ...understanding.costDrivers.map((d) => `- ${d.name}: ${d.mechanism}`),
    "MARGIN DRIVERS:",
    ...understanding.marginDrivers.map((d) => `- ${d.name}: ${d.mechanism}`),
    "COMPETITIVE ADVANTAGES:",
    ...(understanding.competitiveAdvantages || []).map((a) => `- ${a.advantage}: ${a.mechanism}`),
    "COMPETITIVE THREATS:",
    ...(understanding.competitiveThreats || []).map((t) => `- ${t.threat}: ${t.mechanism}`),
    "INFLECTIONS:",
    ...(understanding.currentInflections || []).map((i) => `- ${i}`),
    "",
    "KEY KPIS:",
    ...understanding.keyKpis.map((k) => `- ${k.name} (${k.availability}): ${k.rationale}`),
    "",
    "METRICS TO AVOID (determined by the understanding stage):",
    ...understanding.metricsToAvoid.map((m) => `- ${m.metric} — ${m.reason}`),
    "",
    "FORECAST ASSUMPTIONS (AI model outputs — with historicalEvidence):",
    ...modelSpec.assumptions.map((a) => `- ${a.variable}: ${a.value} ${a.unit} [${a.period}] — ${a.assumption} | evidence: ${a.historicalEvidence.slice(0, 120)} | conf ${a.confidence}`),
    `FORMULAS: ${modelSpec.formulas.map((f) => `[${f.id}] ${f.equation}`).join(" | ")}`,
    "",
    "HISTORICAL DERIVED (deterministic from yfinance):",
    derived,
    "",
    "HISTORICAL FACT ANCHORS (yfinance, up to 40 facts):",
    ...allAnchors,
    ...(evidenceMap
      ? [
          "",
          `EVIDENCE MAP (confidence ${evidenceMap.overallConfidence.toFixed(2)}):`,
          ...evidenceMap.items.slice(0, 12).map((i) => `- [${i.direction}/T${i.tier}] ${i.claim}: ${i.evidence.slice(0, 140)} ${i.factIds.join(" ")}`),
          ...(evidenceMap.unsupported.length ? [`UNSUPPORTED: ${evidenceMap.unsupported.join(" | ")}`] : []),
        ]
      : []),
  ].join("\n");
}

export interface NarrativeOutput {
  thesis: ThesisSpecification;
  catalysts: Catalyst[];
  risks: Risk[];
  competitiveAnalysis: CompetitorAnalysis;
  moat: MoatAnalysis;
}

/** AI narrative generation from fact pack + model spec + optional canonical forecast (single object). */
export async function buildNarrative(
  transport: NarrativeTransport,
  pack: FactPack,
  understanding: CompanyUnderstanding,
  modelSpec: ForecastSpecification,
  canonicalForecast?: any,
  extras?: {
    engine?: EconomicEngine;
    debates?: ThesisEngineOutput;
    evidenceMap?: EvidenceMap;
    discovery?: ResearchDiscoveryPack;
    /** Deterministic ResearchDNA depth emphasis (see depth-guidance.depthBriefForIdentity). */
    depthBrief?: string;
  }
): Promise<NarrativeOutput> {
  const ctx = narrativeContext(pack, understanding, modelSpec, canonicalForecast, extras);
  const user = `RESEARCH CONTEXT
================
${ctx}

TASK
====
Write the research narrative (thesis, catalysts, risks, competitive analysis, moat) for ${understanding.companyName} now. EXPLAIN the research debates and evidence — do not invent new claims.

OUTPUT
======
Respond with ONLY the JSON object.`;

  const resp = await transport({ system: SYSTEM_PROMPT, user, temperature: 0.4, maxTokens: DEPTH_TOKEN_BUDGETS.narrative, jsonMode: true });
  const parsed = parseLlmJson<Record<string, any>>(resp);
  if (!parsed) {
    throw new Error(`AI narrative builder returned unparseable output for ${pack.ticker}`);
  }

  const t = parsed.thesis || {};
  const thesis: ThesisSpecification = {
    thesis: String(t.thesis || ""),
    bullCase: Array.isArray(t.bullCase) ? t.bullCase.map(String) : [],
    bearCase: Array.isArray(t.bearCase) ? t.bearCase.map(String) : [],
    keyDebate: String(t.keyDebate || ""),
    keyInflectionPoints: Array.isArray(t.keyInflectionPoints) ? t.keyInflectionPoints.map(String) : [],
    whatMarketMayBeMissing: String(t.whatMarketMayBeMissing || ""),
    whatCouldInvalidate: Array.isArray(t.whatCouldInvalidate) ? t.whatCouldInvalidate.map(String) : [],
  };

  const catalysts: Catalyst[] = (Array.isArray(parsed.catalysts) ? parsed.catalysts : []).map((c: any) => ({
    catalyst: String(c?.catalyst || ""),
    mechanism: String(c?.mechanism || ""),
    financialVariable: String(c?.financialVariable || ""),
    forecastImpact: typeof c?.forecastImpact === "string" ? c.forecastImpact : undefined,
    valuationImpact: typeof c?.valuationImpact === "string" ? c.valuationImpact : undefined,
    quantitative: c?.quantitative === true,
    timeframe: typeof c?.timeframe === "string" ? c.timeframe : undefined,
    observableKpi: typeof c?.observableKpi === "string" ? c.observableKpi : undefined,
    direction: c?.direction === "negative" || c?.direction === "mixed" || c?.direction === "positive" ? c.direction : undefined,
    invalidation: typeof c?.invalidation === "string" ? c.invalidation : undefined,
  }));

  const risks: Risk[] = (Array.isArray(parsed.risks) ? parsed.risks : []).map((r: any) => ({
    risk: String(r?.risk || ""),
    mechanism: String(r?.mechanism || ""),
    affectedKpi: String(r?.affectedKpi || ""),
    financialConsequence: String(r?.financialConsequence || ""),
    valuationConsequence: String(r?.valuationConsequence || ""),
    monitoringIndicator: String(r?.monitoringIndicator || ""),
  }));

  const comp = parsed.competitiveAnalysis || {};
  const competitiveAnalysis: CompetitorAnalysis = {
    competitors: (Array.isArray(comp.competitors) ? comp.competitors : []).map((c: any) => ({
      company: String(c?.company || ""),
      businessOverlap: String(c?.businessOverlap || ""),
      economicSimilarity: String(c?.economicSimilarity || ""),
      keyDifference: String(c?.keyDifference || ""),
      relativeStrengths: String(c?.relativeStrengths || ""),
      relativeWeaknesses: String(c?.relativeWeaknesses || ""),
      segment: typeof c?.segment === "string" && c.segment ? c.segment : undefined,
    })),
    insufficient: comp.insufficient === true,
    note: typeof comp.note === "string" ? comp.note : undefined,
  };

  const mo = parsed.moat || {};
  const moat: MoatAnalysis = {
    hasMoat: mo.hasMoat === true,
    sources: (Array.isArray(mo.sources) ? mo.sources : []).map((s: any) => ({
      source: String(s?.source || ""),
      evidence: String(s?.evidence || ""),
      economicConsequence: String(s?.economicConsequence || ""),
      durability: String(s?.durability || ""),
      threatsToDurability: String(s?.threatsToDurability || ""),
      chain: typeof s?.chain === "string" && s.chain ? s.chain : undefined,
    })),
    verdict: String(mo.verdict || ""),
  };

  return { thesis, catalysts, risks, competitiveAnalysis, moat };
}

export default { buildNarrative, narrativeContext };